---
groups:
  - name: firehouse-to-sumologic
    jobs: 
    - unit-testing
    - downstream-master
    - unit-testing-master
    - tag-master
    - ship-it
  - name: master
    jobs:
    - downstream-master
    - unit-testing-master
    - tag-master
    - ship-it
  - name: develop
    jobs:
    - unit-testing



jobs:
- name: unit-testing
  public: true
  serial: true
  plan:
   - get: firehouse-to-sumologic-ci 
     resource: firehouse-to-sumologic-develop
     trigger: true
   - task: unit-testing
     file: firehouse-to-sumologic-ci/ci/unit-testing/unit-testing.yml
     

- name: unit-testing-master
  public: true
  serial: true
  plan:
  - get: firehouse-to-sumologic-ci
    resource: firehouse-to-sumologic-master 
    trigger: true
  - task: unit-testing
    file: firehouse-to-sumologic-ci/ci/unit-testing/unit-testing.yml


- name: tag-master
  public: true
  serial: true
  plan:  
  - get: firehouse-to-sumologic-ci
    resource: firehouse-to-sumologic-master 
    passed: [unit-testing-master]
  - put: version
    params: {bump: minor}
  - put: firehouse-to-sumologic-master 
    params: 
      only_tag: true
      repository: firehouse-to-sumologic-ci
      tag: version/number


- name: ship-it
  public: true
  serial: true
  plan:
  - get: firehouse-to-sumologic-ci
    resource: firehouse-to-sumologic-master 
    passed: [tag-master]
    trigger: true
  - get: version
  - task: build-binary
    file: firehouse-to-sumologic-ci/ci/build-all/build-all.yml
    params:
      VERSION_APP: version/number
  - put: gh-release
    params :
      name: version/number
      tag: version/number
      globs:
      - firehouse-to-sumologic-ci-build/dist/*/*/*




- name: downstream-master
  public: true
  serial: true
  plan:
  - aggregate:
    - get: firehouse-to-sumologic-ci
      resource: firehouse-to-sumologic-develop
    - get: release-repo-master
      resource: firehouse-to-sumologic-master 
      trigger: true
      passed: [tag-master]
    - get: release-repo
      resource: firehouse-to-sumologic-merge-target
  - task: merge-master-to-develop
    file: firehouse-to-sumologic-ci/ci/merge-master-to-develop/merge-master-to-develop.yml
    params:
      GIT_USERNAME: {{github-username}}
      GIT_EMAIL:  {{github-email}}




resources:
- name: firehouse-to-sumologic-merge-target
  type: git
  source:
    branch: develop
    private_key: {{private-key-github-concourse}}
    uri: git@github.com:cloudfoundry-community/firehouse-to-sumologic.git

- name: firehouse-to-sumologic-develop
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/firehouse-to-sumologic.git
    branch: develop
    private_key: {{private-key-github-concourse}}

- name: firehouse-to-sumologic-master
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/firehouse-to-sumologic.git
    branch: master
    private_key: {{private-key-github-concourse}}



- name: gh-release
  type: github-release
  source:
    user: cloudfoundry-community
    repository: firehouse-to-sumologic
    access_token: {{github-access-token}}

- name: version
  type: semver-gwenn
  source:
    driver: git
    uri: git@github.com:cloudfoundry-community/firehouse-to-sumologic.git
    branch: version
    file: version
    private_key: {{private-key-github-concourse}}
    git_user: {{concourse-user-gitinfo}}



resource_types:
- name: semver-gwenn
  type: docker-image
  source:
    repository: getourneau/semver-resource


